package Tests;

import java.io.IOException;


public class Test_Faengsel_Amnisti {
    public static void main(String[] args) throws IOException {
        {
            int[] pos_pl1= new int[5];
            int[] pos_pl2= new int[5];
            int[] slag= new int[5];
            int[] chancekort_nr= new int[5];

            pos_pl1[0]=0;

 //           TestSituation tesBetalBanken = new TestSituation(0,0,2,17);

        }
    }
}
